name: CI
on: push
jobs:
  release:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - name: Release
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
      - name: Prepare for deployment
        if: github.ref == 'refs/heads/nanaomoe'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --publish false
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.4.0
        if: github.ref == 'refs/heads/nanaomoe'
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          file: "dist/yuika.zip"
